services:
  backend:
    user: root
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./backend/data/web/static:/backend/data/web/static/
      - ./backend/data/web/media:/backend/data/web/media/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/dotenv_files/.env
    depends_on:
      - psql
  psql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/dotenv_files/.env
      
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"