# Generated by Django 5.2.3 on 2025-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_task_taskuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
