# Generated by Django 5.2.3 on 2025-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_notification_accepted_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='status_task',
            field=models.IntegerField(blank=True, choices=[(1, 'Lembrete'), (2, 'Convite para grupo'), (3, 'Evento no grupo')], default=1, null=True),
        ),
    ]
