# Generated by Django 5.2.3 on 2025-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_taskuser_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuser',
            name='status_task',
            field=models.IntegerField(blank=True, choices=[(1, 'A fazer'), (2, 'Em andamento'), (3, 'Concluído')], default=1, null=True),
        ),
    ]
