# Generated by Django 5.2.3 on 2025-06-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_task_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'A fazer'), (2, 'Em andamento'), (3, 'Concluído')], default=1),
        ),
    ]
